# Generated by Django 3.0.4 on 2020-03-27 21:23

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=accounts.models.profile_image_upload_location)),
                ('age', models.IntegerField(default=10)),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Maried', 'Maried')], max_length=10, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=500)),
                ('address', models.TextField(blank=True, null=True)),
                ('school', models.CharField(blank=True, max_length=500, null=True)),
                ('year_completed', models.BigIntegerField(blank=True, default=1990, null=True)),
                ('qualification', models.CharField(blank=True, choices=[('Higher Secondary', 'Higher Secondary'), ('Bachelor Degree', 'Bachelor Degree'), ('Master Degree', 'Master Degree')], max_length=50, null=True)),
                ('certificate', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=accounts.models.certificate_upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('education_additional_information', models.TextField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=500, null=True)),
                ('job_position', models.CharField(blank=True, max_length=500, null=True)),
                ('salary', models.BigIntegerField(default=0)),
                ('website', models.CharField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('work_experience', models.CharField(blank=True, choices=[('1 Year to 2 Years', '1 Year to 2 Years'), ('2 Yeasr to 3 Years', '2 Years to 3 Years'), ('3 Years to 4 Years', '3 Years to 4 Years'), ('4 Years to 5 Years', '4 Years to 5 Years'), ('5 Years +', '5 Years +')], max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to=accounts.models.resume_upload_location)),
                ('work_additional_information', models.TextField(blank=True, null=True)),
                ('refree_1', models.CharField(blank=True, max_length=100, null=True)),
                ('refree_1_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('refree_2', models.CharField(blank=True, max_length=100, null=True)),
                ('refree_2_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('is_tutor', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_city', to='locations.Location')),
                ('subjects', models.ManyToManyField(blank=True, to='subjects.Subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimony', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts.UserProfile')),
            ],
        ),
    ]
